### ISSUE TITLE
Appears to be incompatible with Storybook 8

### ISSUE THREAD

**Issue by TheAyes** [literalpie/storybook-framework-qwik#71]
I would like to try out the new version but it seems that qwik isn't quite there yet. 

Could someone confirm?
```log
=> Failed to build the preview
Error: [vite]: Rollup failed to resolve import "C:Projektos-js
ode_modules.pnpmstorybook-framework-qwik@0.2.5_@builder.io+qwik@1.4.4_@types+node@20.11.17_sass@1.70.0_typescript@5.3.3_vite@5.1.1
ode_modulesstorybook-framework-qwik" from "/virtual:/@storybook/builder-vite/vite-app.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///C:/Projekte/bos-js/node_modules/.pnpm/vite@5.1.1_@types+node@20.11.17_sass@1.70.0/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:67038:27)
    at onwarn (file:///C:/Projekte/bos-js/node_modules/.pnpm/@builder.io+qwik@1.4.4_@types+node@20.11.17_sass@1.70.0_undici@6.6.2/node_modules/@builder.io/qwik/optimizer.mjs:3397:13)
    at onRollupWarning (file:///C:/Projekte/bos-js/node_modules/.pnpm/vite@5.1.1_@types+node@20.11.17_sass@1.70.0/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:67063:9)
    at onwarn (file:///C:/Projekte/bos-js/node_modules/.pnpm/vite@5.1.1_@types+node@20.11.17_sass@1.70.0/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:66777:13)
    at file:///C:/Projekte/bos-js/node_modules/.pnpm/rollup@4.10.0/node_modules/rollup/dist/es/shared/node-entry.js:17457:13
    at Object.logger [as onLog] (file:///C:/Projekte/bos-js/node_modules/.pnpm/rollup@4.10.0/node_modules/rollup/dist/es/shared/node-entry.js:19117:9)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Projekte/bos-js/node_modules/.pnpm/rollup@4.10.0/node_modules/rollup/dist/es/shared/node-entry.js:18061:26)
    at file:///C:/Projekte/bos-js/node_modules/.pnpm/rollup@4.10.0/node_modules/rollup/dist/es/shared/node-entry.js:18019:26
```
Could also be an issue with storybook or vite. Tho I'm not quite the best at reading stack traces. Would anyone like to point me in a direction? :)

**Comment by literalpie** [comment]
Thanks for the report. I don't see the same error as you, but I'm also unable to get SB to show any stories on storybook 8 with Qwik.

I don't see any errors to point me to the root cause, and unfortunately I have other projects that I need to prioritize over this (at least until SB 8 is closer to release). Of course if anyone in the community wants to look into this, I would welcome it!

**Comment by literalpie** [comment]
I think my patience paid off. It seems like things work with the latest version of SB and Qwik (or maybe I was just doing something wrong last time I tried). 

@TheAyes can you try this again and see if you still get errors? If you do still have issues, please share a Repo with the issue so I can help debug, 🙇🏼

**Comment by TheAyes** [comment]
Hi there!

I've tried again and this time I got actual error messages to read. Still not working tho~
```
> @bosfood/bismuth@ storybook C:\Projekte\bosmono\apps\bismuth
> storybook dev -p 6006

@storybook/cli v8.0.0-rc.1

(node:13768) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
WARN The following packages are incompatible with Storybook 8.0.0-rc.1 as they depend on different major versions of Storybook packages:
WARN - storybook-framework-qwik@0.3.0
WARN  Repo: https://github.com/literalpie/storybook-framework-qwik
WARN 
WARN 
WARN Please consider updating your packages or contacting the maintainers for compatibility details.
WARN For more on Storybook 8 compatibility, see the linked GitHub issue:
WARN https://github.com/storybookjs/storybook/issues/26031
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
info => Starting manager..
info => Starting preview..
[tsconfig-paths] An error occurred while parsing "C:\Projekte\bosmono\tsconfig.json". See below for details. To disable this message, set the `ignoreConfigErrors` option to true.
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/util.js:130:28
    at Array.map (<anonymous>)
    at resolveReferencedTSConfigFiles (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/util.js:129:36)
    at parseReferences (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/parse.js:145:26)
    at Module.parse (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/parse.js:53:52)
    at async Promise.all (index 0)
    at configResolved (C:\Projekte\bosmono\node_modules\.pnpm\vite-tsconfig-paths@4.3.1_typescript@5.3.3_vite@5.1.4\node_modules\vite-tsconfig-paths\src\index.ts:96:9)
    at async Promise.all (index 3)
    at async resolveConfig (file:///C:/Projekte/bosmono/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.24/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67889:5)
    at async getOptimizeDeps (C:\Projekte\bosmono\node_modules\.pnpm\@storybook+builder-vite@7.6.17_typescript@5.3.3_vite@5.1.4\node_modules\@storybook\builder-vite\dist\index.js:159:9031)
[tsconfig-paths] An error occurred while parsing "C:\Projekte\bosmono\packages\shared\tsconfig.json". See below for details.
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/util.js:130:28
    at Array.map (<anonymous>)
    at resolveReferencedTSConfigFiles (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/util.js:129:36)
    at parseReferences (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/parse.js:145:26)
    at Module.parse (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/parse.js:53:52)
    at async Promise.all (index 0)
    at configResolved (C:\Projekte\bosmono\node_modules\.pnpm\vite-tsconfig-paths@4.3.1_typescript@5.3.3_vite@5.1.4\node_modules\vite-tsconfig-paths\src\index.ts:96:9)
    at async Promise.all (index 3)
    at async resolveConfig (file:///C:/Projekte/bosmono/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.24/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67889:5)
    at async getOptimizeDeps (C:\Projekte\bosmono\node_modules\.pnpm\@storybook+builder-vite@7.6.17_typescript@5.3.3_vite@5.1.4\node_modules\@storybook\builder-vite\dist\index.js:159:9031)
[tsconfig-paths] An error occurred while parsing "C:\Projekte\bosmono\tsconfig.json". See below for details. To disable this message, set the `ignoreConfigErrors` option to true.
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/util.js:130:28
    at Array.map (<anonymous>)
    at resolveReferencedTSConfigFiles (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/util.js:129:36)
    at parseReferences (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/parse.js:145:26)
    at Module.parse (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/parse.js:53:52)
    at async Promise.all (index 0)
    at configResolved (C:\Projekte\bosmono\node_modules\.pnpm\vite-tsconfig-paths@4.3.1_typescript@5.3.3_vite@5.1.4\node_modules\vite-tsconfig-paths\src\index.ts:96:9)
    at async Promise.all (index 3)
    at async resolveConfig (file:///C:/Projekte/bosmono/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.24/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67889:5)
    at async _createServer (file:///C:/Projekte/bosmono/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.24/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:64257:20)
[tsconfig-paths] An error occurred while parsing "C:\Projekte\bosmono\packages\shared\tsconfig.json". See below for details.
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/util.js:130:28
    at Array.map (<anonymous>)
    at resolveReferencedTSConfigFiles (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/util.js:129:36)
    at parseReferences (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/parse.js:145:26)
    at Module.parse (file:///C:/Projekte/bosmono/node_modules/.pnpm/tsconfck@3.0.2_typescript@5.3.3/node_modules/tsconfck/src/parse.js:53:52)
    at async Promise.all (index 0)
    at configResolved (C:\Projekte\bosmono\node_modules\.pnpm\vite-tsconfig-paths@4.3.1_typescript@5.3.3_vite@5.1.4\node_modules\vite-tsconfig-paths\src\index.ts:96:9)
    at async Promise.all (index 3)
    at async resolveConfig (file:///C:/Projekte/bosmono/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.24/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67889:5)
    at async _createServer (file:///C:/Projekte/bosmono/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.24/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:64257:20)
╭───────────────────────────────────────────────────────────────╮
│                                                               │
│   Storybook 8.0.0-rc.1 for storybook-framework-qwik started   │
│   467 ms for manager and 7.86 s for preview                   │
│                                                               │
│    Local:            http://localhost:6006/                   │
│    On your network:  http://192.168.55.112:6006/              │
│                                                               │
╰───────────────────────────────────────────────────────────────╯
11:06:09 [vite] Pre-transform error: Failed to resolve import "C:Projektosmono
ode_modules.pnpmstorybook-framework-qwik@0.3.0_@builder.io+qwik@1.4.5_@types+node@20.11.24_typescript@5.3.3_vite@5.1.4
ode_modulesstorybook-framework-qwik" from "../../../../virtual:/@storybook/builder-vite/vite-app.js". Does the file exist?


11:06:09 [vite] Internal server error: Failed to resolve import "C:Projektosmono
ode_modules.pnpmstorybook-framework-qwik@0.3.0_@builder.io+qwik@1.4.5_@types+node@20.11.24_typescript@5.3.3_vite@5.1.4
ode_modulesstorybook-framework-qwik" from "../../../../virtual:/@storybook/builder-vite/vite-app.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/vite-app.js:3:32
  1  |  // Ensure that the client API is initialized by the framework before any other iframe code
  2  |      // is loaded. That way our client-apis can assume the existence of the API+store
  3  |      import { configure } from 'C:\Projekte\bosmono\node_modules\.pnpm\storybook-framework-qwik@0.3.0_@builder.io+qwik@1.4.5_@types+node@20.11.24_typescript@5.3.3_vite@5.1.4\node_modules\storybook-framework-qwik';
     |                                 ^
  4  |
  5  |      const { logger } = __STORYBOOK_MODULE_CLIENT_LOGGER__;
      at formatError (file:///C:/Projekte/bosmono/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.24/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:50529:46)
      at TransformContext.error (file:///C:/Projekte/bosmono/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.24/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:50523:19)
      at normalizeUrl (file:///C:/Projekte/bosmono/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.24/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:65594:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///C:/Projekte/bosmono/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.24/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:65749:47
      at async Promise.all (index 0)
  ❗️ Expect significant performance loss in development.
  ❗️ Disabling the browser's cache results in waterfall requests.
  ```
  
  It also appears that I get quite many tsconfig errors. Maybe I did something wrong there too... uhhh... *sigh*

**Comment by TheAyes** [comment]
I've verified with 7.6.0 and yea the tsconfig errors are there too so that is unrelated.

What isn't there in 7.6.0 is the vite error at the bottom of the log.

**Comment by literalpie** [comment]
Any chance you can share the repo with all the code?

It's possible this is an issue that only happens in Windows. I'll try to find time to see if I can see the error in a fresh project on windows

**Comment by TheAyes** [comment]
I could only offer to see if I can reproduce the issue in a fresh repo.
The repo I usually use is a larger monorepo which partly involves code by my company which may not be published or shared.

**Comment by TheAyes** [comment]
@literalpie Here you have a repo.
https://github.com/TheAyes/bismuth
