### ISSUE TITLE
ReferenceError: window is not defined in Qwik 1.4.2

### ISSUE THREAD

**Issue by literalpie** [literalpie/storybook-framework-qwik#72]
I see this warning in the console when using qwik 1.4.2, but not earlier versions. As far as I can tell, it doesn't actually break anything?

```
11:23:29 AM [vite] Error when evaluating SSR module /Users/benjaminkindle/Developer/temp/dec-qwik-sb/src/routes/layout.tsx:
|- ReferenceError: window is not defined
    at eval (/Users/benjaminkindle/Developer/temp/dec-qwik-sb/src/routes/layout.tsx:17:4)
    at async instantiateModule (file:///Users/benjaminkindle/Developer/temp/dec-qwik-sb/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:54696:9)
```

**Comment by thasmo** [comment]
Experiencing the same with qwik 1.5.4 and storybook 8.1.1.

**Comment by literalpie** [comment]
Is anyone seeing something broken because of this, or is it only the console error?

**Comment by thasmo** [comment]
> Is anyone seeing something broken because of this, or is it only the console error?

Not sure, tbh. Started learning/testing Qwik and Storybook and it's just a bit distracting when trying to figure out things. :)

**Comment by literalpie** [comment]
I believe I included a fix for this [here](https://github.com/literalpie/storybook-framework-qwik/pull/78/files#diff-34373a0a37fa1704bd2e40b94e4f588145487d3f009a2e1ab96fb58cd0c55779R24-R32) as part of a larger "update dependencies" change. This was released as a part of 0.5.0 (along with storybook 9 support/requirement)
