### ISSUE TITLE
Error when evaluating SSR module

### ISSUE THREAD

**Issue by k-schneider** [literalpie/storybook-framework-qwik#74]
I am seeing this error in the terminal when starting storybook after migrating everything to latest:

```
...
"@builder.io/qwik": "^1.5.7",
"@builder.io/qwik-city": "^1.5.7",
...
"@storybook/addon-essentials": "8.1.10",
"@storybook/addon-links": "8.1.10",
"@storybook/blocks": "8.1.10",
"@storybook/builder-vite": "8.1.10",
"@storybook/html": "8.1.10",
"@storybook/html-vite": "8.1.10",
...
"storybook": "8.1.10",
"storybook-framework-qwik": "0.4.0",
...
"vite": "^5.3.1",
"vite-tsconfig-paths": "^4.3.2",
"vitest": "^0.34.6"
```

Full error is:

```
Error when evaluating SSR module C:/path/to/project/src/routes/layout.tsx:
|- ReferenceError: window is not defined
    at eval (C:\path\to\project\src\routes\layout.tsx:33:4)
    at async instantiateModule (file:///C:/path/to/project/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53408:5)
```

The storybook UI still loads and seems to function.

**Comment by literalpie** [comment]
@k-schneider is this fixed for you? I updated dependencies, but didn't do anything specific to try to fix this
